Veewee::Session.declare({
  :boot_cmd_sequence => [
    '<Esc><Esc><Enter>',
    '/install/vmlinuz ',
    'noapic ',
    'preseed/url=http://%IP%:%PORT%/preseed.cfg ',
    'debian-installer=en_US auto locale=en_US kbd-chooser/method=us ',
    'hostname=dev1204 ',
    'fb=false debconf/frontend=noninteractive ',
    'keyboard-configuration/layout=USA keyboard-configuration/variant=USA console-setup/ask_detect=false ',
    'initrd=/install/initrd.gz -- <Enter>'
  ],
  :boot_wait            => '10', 
  :cpu_count            => '1', 
  :disk_format          => 'VMDK', 
  :disk_size            => '10140', 
  :hostiocache          => 'off',
  :iso_download_timeout => '1000',
  :iso_file             => 'ubuntu-12.04.1-server-amd64.iso',
  :iso_md5              => 'a8c667e871f48f3a662f3fbf1c3ddb17',
  :iso_src              => 'http://releases.ubuntu.com/12.04/ubuntu-12.04.1-server-amd64.iso',
  :kickstart_file       => 'preseed.cfg',
  :kickstart_port       => '7122', 
  :kickstart_timeout    => '10000', 
  :memory_size          => '384', 
  :os_type_id           => 'Ubuntu_64',
  :postinstall_files    => [ 'postinstall.sh'], 
  :postinstall_timeout  => '10000',
  :shutdown_cmd         => 'shutdown -P now',
  :ssh_guest_port       => '22',
  :ssh_host_port        => '7222', 
  :ssh_key              => '',
  :ssh_login_timeout    => '10000', 
  :ssh_password         => 'vagrant', 
  :ssh_user             => 'vagrant', 
  :sudo_cmd             => "echo '%p'|sudo -S sh '%f'",
})
