Veewee::Session.declare({
  :boot_cmd_sequence => [
    '<Esc><Esc><Enter>',
    '/install/vmlinuz noapic preseed/url=http://%IP%:%PORT%/preseed.cfg ',
    'debian-installer=en_US auto locale=en_US kbd-chooser/method=us ',
    'hostname=dev.gov.uk ',
    'console-setup/ask_detect=false console-setup/modelcode=pc105 console-setup/layoutcode=us ',
    'initrd=/install/initrd.gz -- <Enter>'
  ],
  :boot_wait            => '10',
  :cpu_count            => '1',
  :disk_format          => 'VDI',
  :disk_size            => '25600',
  :hostiocache          => 'off',
  :iso_download_timeout => '60',
  :iso_file             => 'ubuntu-10.04.4-server-amd64.iso',
  :iso_md5              => '9b218654cdcdf9722171648c52f8a088',
  :iso_src              => 'http://releases.ubuntu.com/10.04.4/ubuntu-10.04.4-server-amd64.iso',
  :kickstart_file       => 'preseed.cfg',
  :kickstart_port       => '7122',
  :kickstart_timeout    => '60',
  :memory_size          => '384',
  :os_type_id           => 'Ubuntu_64',
  :postinstall_files    => [ 'postinstall.sh' ],
  :postinstall_timeout  => '10000',
  :shutdown_cmd         => 'shutdown -P now',
  :ssh_guest_port       => '22',
  :ssh_host_port        => '7222',
  :ssh_key              => '',
  :ssh_login_timeout    => '10000',
  :ssh_password         => 'vagrant',
  :ssh_user             => 'vagrant',
  :sudo_cmd             => "echo '%p'|sudo -S sh '%f'",
})
